project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: images/mylogo.jpg
    background: primary
    foreground: secondary
    left:
      - href: index.qmd
        text: Home
    right:
      - text: "Talks"
        href: talks.html
      - text: "Projects"
        href: projects.html
      - text: "Trainees' Corner"
        menu:
          - text: "Undergraduate"
            href: students.html
          - text: "Membership"
            href: membership.html
          - text: "Fellowship"
            href: fellowship.html
          - text: "Advanced Stats, 2024"
            href: stats2024.html
      - icon: github
        href: https://github.com/sbnguah/ 
      - icon: google
        href: https://scholar.google.com/citations?user=gbehSqQAAAAJ&hl=en
      - icon: twitter
        href: https://twitter.com/NguahSamue66067/
      - icon: linkedin
        href: https://www.linkedin.com/in/samuel-blay-nguah-4423a410/
        


format:
  html:
    theme: cerulean
    mainfont: Times New
    fontsize: 18px
    css: styles.css
    toc: true

editor: visual


  
  
