project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - text: "Pediatrics"
        href: pedics.html
      - text: "Research"
        href: research.html
      - text: "Talks"
        href: talks.html
      - text: "Projects"
        href: projects.html
      - text: "Trainees"
        menu:
          - text: "Undergraduate"
            href: students.html
          - text: "Membership"
            href: membership.html
          - text: "Fellowship"
            href: fellowship.html 
      - icon: fab fa-github
        href: https://github.com/sbnguah/ 


format:
  html:
    theme: united
    mainfont: Times New
    fontsize: 18px
    css: styles.css
    toc: true

editor: visual


  
  
