project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - text: "Workshops"
        menu:
          - text: "Adv. Stats 2024"
          - href: adv-stats-2024.html
      - text: "Talks"
        href: talks.html
      - text: "Projects"
        href: projects.html
      - text: "Trainees' Corner"
        menu:
          - text: "Undergraduate"
            href: students.html
          - text: "Membership"
            href: membership.html
          - text: "Fellowship"
            href: fellowship.html 
      - icon: fab fa-github
        href: https://github.com/sbnguah/ 
      - icon: twitter
        href: https://twitter.com/NguahSamue66067/


format:
  html:
    theme: cerulean
    mainfont: Times New
    fontsize: 18px
    css: styles.css
    toc: true

editor: visual


  
  
