---
title: "Research Projects"
date: today
description: A description of my past and ongoing research
bibliography: references.bib
---

<hr>

### PINGS-2

The PINGS-2 (Phone-Based Intervention under Nurse Guidance after Stroke) is a multicenter randomized
controlled trial where routine care of patients who had a recent stroke is compared to those who
have nursing support in managing their blood pressure after the stroke. Some of the publications
emanating from this project are @sarfo2021

<hr>

### PedEcho

This is a review of electrocardiograms done in pediatric patients in Kumasi since 2010. It seeks to
bring out the common echocardiographic diagnosis and its changing patterns over the years.

<hr>

### SPARCo

The Sickle Pan-African Consortium (SPARCO-II) consists of a hub in East Africa (Tanzania) and
collaborative consortium sites in West Africa (Ghana, Nigeria) and Central Africa (Cameroon,
Democratic Republic of Congo) which will expand to form the Sickle Pan-African Network involving 20
sites in 15 countries. This consortium is into research involving every aspect of Sickle Cell
Disease in both children and adults. Some publications arising from this study include
@oppong-mensah2023

<hr>

### Pediatric Weight Estimation

This is a study done in both Kumasi and Tamale to determine the accuracy of the various pediatric
weight estimation methods. In the study done at the Child Department of the Tamale Teaching
Hospital, children presenting with medical emergencies were recruited. The study done at the Komfo
Anokye Teaching Hospital however recruited children with Sickle Cell Disease, Cardiac Pathologies,
and those with chronic medical conditions attending the specialist outpatient clinic. Publications
arising from these studies include @cosmosyakubu2022 and @yakubu2023
