---
title: "Data Description"
author: "Samuel Blay Nguah"
date: "2024-02-15"
categories: [Other]
---

This post describes the data set to be used in the workshop.

## ANCData

**Description**\
This dataset can be downloaded from [here](ANCData.xlsx). It contains records of high-risk pregnant
women under a trial on new and old methods of antenatal care in two clinics. The outcome was
perinatal mortality. There are 755 observations with the following 3 variables.

-   **death**: A categorical variable indicating if death occurred in the infant.
-   **anc**: Indicates which type of ANC method was used.
-   **clinic**: Indicates which clinic the patient was seen at.

## blood

**Description**\
This dataset can be downloaded from [here](blood.xlsx). It contains records of a cross-sectional
study of the blood results of 50 children. It has the following 7 variables.

-   **stno**: The study ID.
-   **age**: Age in completed months of the study participants.
-   **wgt**: Weight in kilogram
-   **hgt**: Height in cms
-   **hb**: Blood hemoglobin concentration in g/dL
-   **wbc**: White blood cell count
-   **hct**: Blood hematocrit in %

## titanic

**Description**\
This dataset can be downloaded from [here](titanic.xlsx). It contains records of the fateful journey
by the Titanic cruise ship. It has the following 5 variables.

-   **class**: The class in which the person was.
-   **age**: Age in completed years.
-   **sex**: Sex
-   **survived**: Whether the person survived the sinking of the ship
-   **died**: Whether the person died as a result of the accident

## schisto

**Description**\
This dataset can be downloaded from [here](schisto.xlsx). It was obtained from 367 pupils in a
community in Ghana. The cross-sectional study was to determine the effect of urinary schistosomiasis
on the nutritional status as well as blood indices of school children. It has the following 15
variables.

-   **Serial0**: The study ID.
-   **Q3Age**: Age in completed years.
-   **Q4Sex**: The sex of the pupil.
-   **Q35weight**: Weight in kilogram
-   **Q36Height**: Height in cms
-   **Q6Religion**: Religious affiliation
-   **Educationalstatus**: Level of education
-   **Q15PipeBorne**: Does the pupil use bipe-borne water at home? 0 = No, 1 = Yes
-   **Q15Well**: Does the pupil use well water at home? 0 = No, 1 = Yes
-   **Q15River**: Does the pupil use river water at home? 0 = No, 1 = Yes
-   **HB**: Blood hemoglobin concentration in g/dL
-   **SH**: Shistosomiasis ova in the urine. Nil, +, ++, and +++
-   **HCT**: Blood hematocrit in %
-   **MCV**: Mean Corpuscular Volume
-   **MCH**: Mean Corpuscular Hemoglobin

## NewDrug

**Description**\
This dataset can be downloaded from [here](NewDrug.dta). It was obtained in a randomized controlled
trial of a new drug against a control drug. It measured the mean blood pressure of study
participants before and after the drugs were administered. It has the following 6 variables.

-   **id**: Study ID
-   **treat**: Treatment given
-   **age**: Age in completed years.
-   **sex**: Gender of participant
-   **bp1**: Mean arterial BP before treatment
-   **bp2**: Mean arterial BP after treatment

## Outbreak

**Description**  
This data can be downloaded from [here](Outbreak.rds). It contains information 
from an outbreak investigation concerning food poisoning on a sportsday in 
Thailand 1990.

Dichotomous variables for exposures and symptoms were coded as 0 = No, 1 = yes 
and 9 = Missing.  

It contains the following variables  

- **id**: Study ID 
- **sex**: Sex of study person. 0 = Female, 1 = Male. 
- **age**: Age of participant. 99 = Missing 
- **exptime**: Character version of time of exposure 
- **beefcurry**: Whether the subject ate beef curry 
- **saltegg**: Whether the subject ate salted eggs 
- **eclair**: Pieces of eclair eaten by participants. 80 = "ate but could not remember
how much", 90 = totally missing information 
- **water**: Whether the subject drunk water 
- **onset**: Character version of time of onset 
- **nausea**: Whether the subject had nausea 
- **vomiting**: Whether the subject had vomiting 
- **abdpain**: Whether the subject had abdominal pain 
- **diarrhea**: Whether the subject had diarrhea
